### ISSUE TITLE
[jacobsen on 2007-06-07 19:12:42] : domapptest.py fails on pcts-hub01

### ISSUE THREAD

**Issue by arcor** [WIPACrepo/domapp-tools-python#11]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 414, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 402, in run
    apply(self.__target, self.__args, self.__kwargs)
  File "/usr/bin/domapptest.py", line 607, in runThread
    self.doAllTests(domid, c,w,d)
  File "/usr/bin/domapptest.py", line 581, in doAllTests
    test.run(dor.fd)
  File "/usr/bin/domapptest.py", line 168, in run
    ok, txt = self.dor.isInIceboot()
TypeError: unpack non-sequence

Steps to Reproduce: b"''"

Additional Information: b"''"

**Comment by arcor** [comment]
[jacobsen on 2007-06-07 19:46:44]
i changed the MiniDor.py interface in an inconsistent way

**Comment by arcor** [comment]
[jacobsen on 2007-06-07 19:48:29]
Sending        README.txt
Sending        domapptest.py
Sending        domapptools/MiniDor.py
Transmitting file data ...
[commit 6279f83ef0fd73146657edd15a3bc7fd314d1b4b] Committed revision 1578.

**Comment by arcor** [comment]
[jacobsen on 2007-06-08 20:02:26]
resolved w/ last commit
